title: Barcode Reader Emulator
logo: https://raw.githubusercontent.com/oxcafedead/barcode-reader-emulator/main/docs/screenshot.jpg
theme: jekyll-theme-minimal
show_downloads: true
version: 2.0.0-alpha
github:
  url: https://github.com/oxcafedead/barcode-reader-emulator/releases/download/2.0.0-alpha/barcode-emulator.exe
