title: Barcode Reader Emulator
logo: https://raw.githubusercontent.com/oxcafedead/barcode-reader-emulator/main/docs/screenshot.png
theme: jekyll-theme-minimal
show_downloads: true
version: 0.4.1
github:
  zip_url: https://github.com/oxcafedead/barcode-reader-emulator/releases/download/0.4.1/emulator.zip
